language: go
go:
  - 1.11.x

# internal package import시 사용
go_import_path: github.com/opklnm102/echo-sample
  
env:
  - DEP_VERSION="0.5.0"

# cache:
#  directories:
#    - ${TRAVIS_BUILD_DIR}/vendor

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: echo "not master build ${TRAVIS_COMMIT}"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master
    skip_cleanup: true
  - provider: script
    script: bash build
    on:
      all_branches: true
  - provider: script
    script: echo "master build tagging latest"
    on:
      branch: master
  - provider: script
    script: echo "tag build ${TRAVIS_TAG}"
    on:
      tags: true
